version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./cvas_data.json:/app/cvas_data.json